In [1]:
import numpy as np

In [2]:
l= [1,2,3,4,5,6]

In [9]:
a1 = np.array(l)

In [4]:
l1 = [4,5,6,7,"sudh", 34.56, True]

In [10]:
np.array(l1)

In [12]:
a2 = np.array([[1,2,3],[4,5,6]])

In [11]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
a1

array([1, 2, 3, 4, 5, 6])

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
a1.ndim #dimension of array a1

1

In [17]:
a2.ndim #dimension of array a2

2

In [19]:
a3.ndim #dimension of array a3

3

In [20]:
np.random.randint(2,50 ,(3,4) )

array([[20, 32, 35, 40],
       [48, 44, 31, 30],
       [19,  7,  2, 46]])

In [22]:
np.random.randint(5,50,(3,3))

array([[47, 20, 39],
       [38, 41, 11],
       [10, 32, 18]])

In [23]:
a1.size #size tells us total number of elements in an array

6

In [24]:
a2.size

6

In [25]:
a3.size

9

In [26]:
a1.shape #tells shape - 1 row no column

(6,)

In [27]:
a2.shape  #2 row, 3 col

(2, 3)

In [28]:
a3.shape #1 metrics 3x3 : right to left x 3, y 3, z 1

(1, 3, 3)

In [29]:
a1

array([1, 2, 3, 4, 5, 6])

In [30]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a4 = np.random.randint(2,5)

In [34]:
a4

3

In [36]:
np.random.randint(2,50,(2,2))

array([[43, 28],
       [49, 47]])

In [37]:
np.random.randint(2,50,(3,4)) #3x4 - 2 dimension matrix integer matrix

array([[37, 45, 41, 36],
       [14, 48, 18, 43],
       [17, 10, 36,  3]])

In [39]:
np.random.randint(2,50,(2,3,4)) # 2 matrices of 3 x 4

array([[[ 3, 45, 30, 46],
        [43, 12, 12,  9],
        [22, 14, 38,  8]],

       [[ 6, 13, 33,  7],
        [ 8, 14, 11,  2],
        [47, 28, 12, 12]]])

In [47]:
np.random.rand(2,3) #float matrix

array([[0.93544839, 0.9131861 , 0.74254155],
       [0.03442089, 0.9222972 , 0.04323037]])

In [50]:
 np.random.randn(4,4) #normally distributed data set, : average = 0, std deviation = 1

array([[-2.01246312, -0.40273385, -0.61472674,  0.35502822],
       [-0.75298547, -0.06397377,  0.10136579,  0.88704537],
       [ 0.19851557, -0.13143159, -0.0138968 , -1.13735555],
       [-0.86513713, -1.06732716,  1.47780117,  0.55810896]])

In [51]:
avg(-2.0124,-0.7529,0.19851,-0.86513)

NameError: name 'avg' is not defined

In [53]:
a5 = np.random.randn(4,4) #16 elements

In [54]:
a5

array([[ 0.2824854 , -0.13270295,  0.11715383, -0.23013689],
       [ 0.97823087,  0.83944062, -0.20795481,  0.30453885],
       [-0.29134457, -0.40895828, -1.01468498,  1.61539075],
       [-1.14212801,  1.31789144,  1.24621842,  0.55697456]])

In [57]:
a5.reshape(2,8) #4x4 matrix reshaped to 2x4 = 16 elements

array([[ 0.2824854 , -0.13270295,  0.11715383, -0.23013689,  0.97823087,
         0.83944062, -0.20795481,  0.30453885],
       [-0.29134457, -0.40895828, -1.01468498,  1.61539075, -1.14212801,
         1.31789144,  1.24621842,  0.55697456]])

In [59]:
a5.reshape(8,2) #8 x 2

array([[ 0.2824854 , -0.13270295],
       [ 0.11715383, -0.23013689],
       [ 0.97823087,  0.83944062],
       [-0.20795481,  0.30453885],
       [-0.29134457, -0.40895828],
       [-1.01468498,  1.61539075],
       [-1.14212801,  1.31789144],
       [ 1.24621842,  0.55697456]])

In [60]:
a5.reshape(16,1) # 16 rows, 1 col

array([[ 0.2824854 ],
       [-0.13270295],
       [ 0.11715383],
       [-0.23013689],
       [ 0.97823087],
       [ 0.83944062],
       [-0.20795481],
       [ 0.30453885],
       [-0.29134457],
       [-0.40895828],
       [-1.01468498],
       [ 1.61539075],
       [-1.14212801],
       [ 1.31789144],
       [ 1.24621842],
       [ 0.55697456]])

In [61]:
a5.reshape(1,16) 

array([[ 0.2824854 , -0.13270295,  0.11715383, -0.23013689,  0.97823087,
         0.83944062, -0.20795481,  0.30453885, -0.29134457, -0.40895828,
        -1.01468498,  1.61539075, -1.14212801,  1.31789144,  1.24621842,
         0.55697456]])

In [62]:
a5.reshape(2,-1) #not give error, when we give negative number, numpy will detect the shape, # work with any begative num

array([[ 0.2824854 , -0.13270295,  0.11715383, -0.23013689,  0.97823087,
         0.83944062, -0.20795481,  0.30453885],
       [-0.29134457, -0.40895828, -1.01468498,  1.61539075, -1.14212801,
         1.31789144,  1.24621842,  0.55697456]])

In [63]:
a5.reshape(4,-2) #4 X 4

array([[ 0.2824854 , -0.13270295,  0.11715383, -0.23013689],
       [ 0.97823087,  0.83944062, -0.20795481,  0.30453885],
       [-0.29134457, -0.40895828, -1.01468498,  1.61539075],
       [-1.14212801,  1.31789144,  1.24621842,  0.55697456]])

In [65]:
a5.reshape(2,2,4) #reshaping it as 2 matrixes of 2 x 4

array([[[ 0.2824854 , -0.13270295,  0.11715383, -0.23013689],
        [ 0.97823087,  0.83944062, -0.20795481,  0.30453885]],

       [[-0.29134457, -0.40895828, -1.01468498,  1.61539075],
        [-1.14212801,  1.31789144,  1.24621842,  0.55697456]]])

In [66]:
a5.reshape(1,1,2,2,4)

array([[[[[ 0.2824854 , -0.13270295,  0.11715383, -0.23013689],
          [ 0.97823087,  0.83944062, -0.20795481,  0.30453885]],

         [[-0.29134457, -0.40895828, -1.01468498,  1.61539075],
          [-1.14212801,  1.31789144,  1.24621842,  0.55697456]]]]])

In [67]:
a1

array([1, 2, 3, 4, 5, 6])

In [68]:
a1[2:6]

array([3, 4, 5, 6])

In [69]:
a1[0]

1

In [70]:
a6 = np.array(l1)

In [71]:
a6

array(['4', '5', '6', '7', 'sudh', '34.56', 'True'], dtype='<U32')

In [74]:
a6[2:6]

array(['6', '7', 'sudh', '34.56'], dtype='<U32')

In [75]:
a6[0:6:2] #slicing

array(['4', '6', 'sudh'], dtype='<U32')

In [76]:
a6[::-1] #reversing array

array(['True', '34.56', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [77]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a2[1]

array([4, 5, 6])

In [82]:
a2 [0:1]

array([[1, 2, 3]])

In [83]:
a2[1:0]

array([], shape=(0, 3), dtype=int32)

In [81]:
a2[0:1,1] #slicing of array not understood

array([2])

In [84]:
a2[::]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
a2[:1:]

array([[1, 2, 3]])

In [86]:
a2[:1,1:]

array([[2, 3]])

In [87]:
a2[:1,:]

array([[1, 2, 3]])

In [88]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [91]:
a2[[0,1],[1,2]]

array([2, 6])

In [93]:
a6 = np.random.randint(2,90 , (6,5))

In [94]:
a5


array([[61, 87, 52, 21, 37],
       [23, 58, 13, 74, 28],
       [42, 30, 80, 84, 56],
       [17, 45, 48, 69, 53],
       [35, 47, 11, 11, 24],
       [54, 53, 20, 50,  6]])

In [95]:
a5[a5>40]

array([61, 87, 52, 58, 74, 42, 80, 84, 56, 45, 48, 69, 53, 47, 54, 53, 50])

In [96]:
a5[0,1] = 100

In [97]:
a5

array([[ 61, 100,  52,  21,  37],
       [ 23,  58,  13,  74,  28],
       [ 42,  30,  80,  84,  56],
       [ 17,  45,  48,  69,  53],
       [ 35,  47,  11,  11,  24],
       [ 54,  53,  20,  50,   6]])

In [98]:
a6

array([[35,  9, 32, 62, 49],
       [52, 57, 32, 66, 40],
       [ 6, 77,  6, 78, 56],
       [65, 29, 76, 35, 25],
       [ 8, 34, 83, 12, 69],
       [66, 86, 88, 61, 45]])

In [99]:
a6 = np.random.randint(0,3 , (3,3))

In [100]:
a6


array([[0, 1, 0],
       [2, 1, 1],
       [0, 0, 1]])

In [101]:
a7 = np.random.randint(0,3 , (3,3))

In [102]:
a7

array([[1, 0, 0],
       [0, 2, 2],
       [1, 0, 2]])

In [103]:
a6*a7 #element multiplication not random multiplication

array([[0, 0, 0],
       [0, 2, 2],
       [0, 0, 2]])

In [104]:
a6@a7 #matrix multiplication

array([[0, 2, 2],
       [3, 2, 4],
       [1, 0, 2]])

In [105]:
a6+100

array([[100, 101, 100],
       [102, 101, 101],
       [100, 100, 101]])

In [106]:
a6*2

array([[0, 2, 0],
       [4, 2, 2],
       [0, 0, 2]])

In [107]:
a8 = np.zeros((4,4))

In [108]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
a9  = np.ones((4,5))

In [110]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [112]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [115]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [116]:
a9.T

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:
a6.T

array([[0, 2, 0],
       [1, 1, 0],
       [0, 1, 1]])

In [118]:
a5

array([[ 61, 100,  52,  21,  37],
       [ 23,  58,  13,  74,  28],
       [ 42,  30,  80,  84,  56],
       [ 17,  45,  48,  69,  53],
       [ 35,  47,  11,  11,  24],
       [ 54,  53,  20,  50,   6]])

In [119]:
np.sqrt(a5)

array([[ 7.81024968, 10.        ,  7.21110255,  4.58257569,  6.08276253],
       [ 4.79583152,  7.61577311,  3.60555128,  8.60232527,  5.29150262],
       [ 6.4807407 ,  5.47722558,  8.94427191,  9.16515139,  7.48331477],
       [ 4.12310563,  6.70820393,  6.92820323,  8.30662386,  7.28010989],
       [ 5.91607978,  6.8556546 ,  3.31662479,  3.31662479,  4.89897949],
       [ 7.34846923,  7.28010989,  4.47213595,  7.07106781,  2.44948974]])

In [120]:
np.exp(a5)

array([[3.10429794e+26, 2.68811714e+43, 3.83100800e+22, 1.31881573e+09,
        1.17191424e+16],
       [9.74480345e+09, 1.54553894e+25, 4.42413392e+05, 1.37338298e+32,
        1.44625706e+12],
       [1.73927494e+18, 1.06864746e+13, 5.54062238e+34, 3.02507732e+36,
        2.09165950e+24],
       [2.41549528e+07, 3.49342711e+19, 7.01673591e+20, 9.25378173e+29,
        1.04137594e+23],
       [1.58601345e+15, 2.58131289e+20, 5.98741417e+04, 5.98741417e+04,
        2.64891221e+10],
       [2.83075330e+23, 1.04137594e+23, 4.85165195e+08, 5.18470553e+21,
        4.03428793e+02]])

In [121]:
np.log10(a5)

array([[1.78532984, 2.        , 1.71600334, 1.32221929, 1.56820172],
       [1.36172784, 1.76342799, 1.11394335, 1.86923172, 1.44715803],
       [1.62324929, 1.47712125, 1.90308999, 1.92427929, 1.74818803],
       [1.23044892, 1.65321251, 1.68124124, 1.83884909, 1.72427587],
       [1.54406804, 1.67209786, 1.04139269, 1.04139269, 1.38021124],
       [1.73239376, 1.72427587, 1.30103   , 1.69897   , 0.77815125]])

In [7]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns

In [123]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=7a792f7417db053a01b9272511998b2e0d0c0776d2a4a4678d59e54f5e5a12e5
  Stored in directory: c:\users\shriramm\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [124]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [125]:
cf.go_offline()

In [8]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A' , 'B' ,'C'])

In [9]:
df

A         B         C
0  -1.761109 -1.408272  0.886862
1   1.754545 -1.629455 -0.851973
2  -1.396003 -0.373503  2.029731
3   0.067837  0.231968  1.618754
4  -1.433595 -0.063667 -0.041412
..       ...       ...       ...
95  0.033144  1.224462  0.460881
96 -0.694523 -0.371199  0.580470
97 -0.520719 -0.234195 -0.394945
98 -0.314816 -1.338318 -0.509005
99 -1.015585 -0.132654 -0.771563

[100 rows x 3 columns]

In [10]:
df.iplot()

PlotlyRequestError: Authentication credentials were not provided.